#%RAML 1.0 
title: Episode IV A New Hope
version: 1.0
description: The 4th episode of the Star Wars saga

uses: 
  characterType: exchange_modules/fc391f6f-5b49-4286-a172-f64346cc1c1d.lucas-films/charactertype/1.0.1/charactertype.raml

types: 
  character: characterType.character

/character:
  description: Work with the characters of the film
  get:
    description: Retrieve a list of characters
    queryParameters: 
      characterType: 
        displayName: Character Type
        type: string
        description: The type of character to be queried
        required: false
    responses:
      200:
        body: 
          application/json:
            type: character[]
            example: !include exchange_modules/fc391f6f-5b49-4286-a172-f64346cc1c1d.lucas-films/charactercollectionexample/1.0.0/charactercollectionexample.raml
/opening_crawl:
  get:
    description: Get the film's opening crawls
    responses: 
      200:
        body: 
          application/json:
            example: !include exchange_modules/fc391f6f-5b49-4286-a172-f64346cc1c1d.lucas-films/openingcrawlexample/1.0.0/openingcrawlexample.raml