#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/ced23e20-2510-436c-94a4-3a6a51446fd8/mocks/af4d9c18-7b80-4e72-af3f-f3fd7cdfe89d/mocks/bdf4047f-171c-4e52-a2c6-7ee4be01ef37 # baseUri: https://mocksvc.mulesoft.com/mocks/af4d9c18-7b80-4e72-af3f-f3fd7cdfe89d/mocks/bdf4047f-171c-4e52-a2c6-7ee4be01ef37 # baseUri: https://mocksvc.mulesoft.com/mocks/bdf4047f-171c-4e52-a2c6-7ee4be01ef37 # 
title: StarWars
version: v6
description: Episode 6 Return of the Jedi

uses: 
  characterType: exchange_modules/fc391f6f-5b49-4286-a172-f64346cc1c1d.lucas-films/charactertype/1.0.2/charactertype.raml

types: 
  character: characterType.character

/character:
  description: Work with the characters of the film
  get:
    description: Retrieve a list of characters
    queryParameters: 
      species:
        description: Specify the type of species to retrieve
        type: string
        required: false
    responses:
      200:
        body: 
          application/json:
            type: character[]
            example: !include exchange_modules/fc391f6f-5b49-4286-a172-f64346cc1c1d.lucas-films/charactercollectionexample/1.0.0/charactercollectionexample.raml
  post:
    description: Create a new character
    body: 
      application/json:
        type: character
        example: !include exchange_modules/fc391f6f-5b49-4286-a172-f64346cc1c1d.lucas-films/charactersingleexample/1.1.0/charactersingleexample.raml
    responses: 
      201:
        body: 
          application/json:
            example: {message: "New Character created successfully"}
/opening_crawl:
  get:
    description: Get the film's opening crawls
    responses: 
      200:
        body: 
          application/json:
            example: !include exchange_modules/fc391f6f-5b49-4286-a172-f64346cc1c1d.lucas-films/openingcrawlexample/1.0.0/openingcrawlexample.raml